version: 2.1
jobs:
  install_aws_cli:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install packages
          command: |
            make register_task_definition


workflows:
  workflow_test:
    jobs:
      - install_aws_cli:
          context: AWS