version: 2.1
parameters:
  Username:
    type: string
    default: copy
jobs:
  ECS:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "checking"
          command: |
            if [ $CIRCLE_USERNAME == "" ]
              echo "empty"
      - run:
          name: calling makefile
          command: |
            echo "helloworld"
            echo $CIRCLE_USERNAME


workflows:
  workflow_test:
    jobs:
      - ECS:
          context: AWSNCLOUDS
