version: 2.1
jobs:
  install_aws_cli:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          command: |
            make install_awscli


workflows:
  workflow_test:
    jobs:
      - install_aws_cli