version: 2.1
jobs:
  install_aws_cli:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: pipeline
          command: |
            make install_awscli
            make push_image
            make register_task_definition
            make deploy_ecs
            


workflows:
  workflow_test:
    jobs:
      - install_aws_cli:
          context: AWS