version: 2.1
jobs:
  number_one:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: "Running the file"
          command: |
            . venv/bin/activate
            python3 main.py
      
        - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
        - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file
          
workflows:
  workflow_test:
    jobs:
      - number_one:
          filters:
            branches:
              only:
               - master





#version: 2.1

#jobs:
#  number_one:
#    docker:
#      - image: cimg/base:2021.04

#    steps:
#      - checkout
#      - run:
#          name: "make_python_file"
#          command: touch main.py
#      - run:
#          name: "writing_command"
#          command: print("Hello world") > main.py
#      - run:
#          name: "run file"
#          command: python main.py
#workflows:
#  workflow_test:
#    jobs:
#      - number_one