version: 2.1
jobs:
  ECS:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: calling makefile
          command: |
            sudo apt install python3-pip
            


workflows:
  workflow_test:
    jobs:
      - ECS:
          context: AWS