version: 2.1
parameters:
  Username:
    type: string
    default: TAGANCH
jobs:
  ECS:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "checking"
          command: |
              if [[ -z "<< pipeline.parameters.Username >>" ]]; then
                echo "export TAGANCH=hellower" >> $BASH_ENV
                else echo "export TAGANCH=nothellower" >> $BASH_ENV
              fi
      - run:
          name: calling makefile
          command: |
            echo "helloworld"
            echo << pipeline.parameters.Username >>


workflows:
  workflow_test:
    jobs:
      - ECS:
          context: AWSNCLOUDS
