version: 2.1
parameters:
  Username:
    type: string
    default: $CIRCLE_USERNAME
jobs:
  ECS:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: calling makefile
          command: |
            echo "username = << pipeline.parameters.Username >>"
            echo "helloworld"


workflows:
  workflow_test:
    jobs:
      - ECS:
          context: AWSNCLOUDS
