version: 2.1
parameters:
  Username:
    type: string
    default: username
jobs:
  ECS:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "checking"
          command: |
            if [ $CIRCLECI_USERNAME -eq "" ] then
              echo "export << pipeline.parameters.Username >>=testing" >> "testing1"
              else echo "hello"
            fi
      - run:
          name: calling makefile
          command: |
            echo "username = << pipeline.parameters.Username >>"
            echo "helloworld"


workflows:
  workflow_test:
    jobs:
      - ECS:
          context: AWSNCLOUDS
