version: 2.1
jobs:
  ECS:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: calling makefile
          command: |
            make install_awscli_packages 
            make build_image
            make tag_image
            make push_image
            make ecs_deploy_packages
            make deploy_ecs_cluster


workflows:
  workflow_test:
    jobs:
      - ECS:
          context: AWSNCLOUDS